import { create } from 'zustand';

type Language = 'es' | 'en';

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Index
    'hero.subtitle': 'Conoce tus probabilidades antes de pelear. Optimiza tu build en segundos.',
    'cta.simulate': 'Simular PVP',
    'cta.optimize': 'Optimizar Build',
    'feature.simulator.title': 'Simulador de Matchups PVP',
    'feature.simulator.desc': 'Ingresa tu build y la de tu rival para obtener un análisis instantáneo con probabilidad de victoria, fortalezas y estrategias.',
    'feature.optimizer.title': 'Optimizador de Build',
    'feature.optimizer.desc': 'Dinos tu objetivo (PVP, Farmeo o Boss) y obtén una ruta de mejora personalizada con la mejor fruta, arma y stats.',
    'stats.fruits': 'Frutas',
    'stats.weapons': 'Armas',
    'stats.free': 'Gratis',
    'footer.disclaimer': 'Herramienta fan-made. No afiliada con Blox Fruits o Roblox.',
    // Simulator
    'simulator.title': 'Simulador PVP',
    'simulator.subtitle': 'Compara builds y conoce tus probabilidades',
    'simulator.your_build': 'Tu Build',
    'simulator.rival_build': 'Build Rival',
    'simulator.level': 'Nivel',
    'simulator.fruit': 'Fruta',
    'simulator.weapon': 'Arma',
    'simulator.style': 'Estilo de Pelea',
    'simulator.stats': 'Enfoque de Stats',
    'simulator.simulate': 'Simular Matchup',
    'simulator.why_score': 'Por Qué Este Puntaje',
    'simulator.how_improve': 'Cómo Mejorar',
    'simulator.tips': 'Tips de Batalla',
    'simulator.new': 'Nueva Simulación',
    'simulator.share': 'Compartir Resultado',
    'simulator.confidence': 'Confianza',
    // Optimizer
    'optimizer.title': 'Optimizador de Build',
    'optimizer.subtitle': 'Obtén tu build perfecta en segundos',
    'optimizer.goal': '¿Cuál es Tu Objetivo?',
    'optimizer.pvp': 'Dominar PVP',
    'optimizer.pvp_desc': 'Ganar más duelos',
    'optimizer.farm': 'Farmeo Eficiente',
    'optimizer.farm_desc': 'Limpiar mobs más rápido',
    'optimizer.boss': 'Mata Bosses',
    'optimizer.boss_desc': 'Derrotar bosses fácilmente',
    'optimizer.current': 'Build Actual (Opcional)',
    'optimizer.current_desc': 'Dinos qué tienes para construir sobre eso',
    'optimizer.current_fruit': 'Fruta Actual',
    'optimizer.current_weapon': 'Arma Actual',
    'optimizer.keep_fruit': 'Mantener mi fruta',
    'optimizer.keep_weapon': 'Mantener mi arma',
    'optimizer.optimize': 'Optimizar Mi Build',
    'optimizer.recommended': 'Build Recomendada',
    'optimizer.tier': 'Tier',
    'optimizer.upgrade_path': 'Ruta de Mejora',
    'optimizer.new': 'Nueva Optimización',
    // Common
    'select.fruit': 'Seleccionar fruta...',
    'select.weapon': 'Seleccionar arma...',
    'select.style': 'Seleccionar estilo...',
    'none_selected': 'Ninguno seleccionado...',
    'balanced': 'Balanceado',
    'melee': 'Melee',
    'fruit': 'Fruta',
    'defense': 'Defensa',
    'favorable': 'FAVORABLE',
    'neutral': 'NEUTRAL',
    'unfavorable': 'DESFAVORABLE',
  },
  en: {
    // Index
    'hero.subtitle': 'Know your odds before you fight. Optimize your build in seconds.',
    'cta.simulate': 'Simulate PVP',
    'cta.optimize': 'Optimize Build',
    'feature.simulator.title': 'PVP Matchup Simulator',
    'feature.simulator.desc': 'Enter your build and your rival\'s to get instant matchup analysis with win probability, strengths, and counter strategies.',
    'feature.optimizer.title': 'Build Optimizer',
    'feature.optimizer.desc': 'Tell us your goal (PVP, Farming, or Boss) and get a personalized upgrade path with the best fruit, weapon, and stats.',
    'stats.fruits': 'Fruits',
    'stats.weapons': 'Weapons',
    'stats.free': 'Free',
    'footer.disclaimer': 'Fan-made tool. Not affiliated with Blox Fruits or Roblox.',
    // Simulator
    'simulator.title': 'PVP Simulator',
    'simulator.subtitle': 'Compare builds and know your odds',
    'simulator.your_build': 'Your Build',
    'simulator.rival_build': 'Rival Build',
    'simulator.level': 'Level',
    'simulator.fruit': 'Fruit',
    'simulator.weapon': 'Weapon',
    'simulator.style': 'Fighting Style',
    'simulator.stats': 'Stat Focus',
    'simulator.simulate': 'Simulate Matchup',
    'simulator.why_score': 'Why This Score',
    'simulator.how_improve': 'How to Improve',
    'simulator.tips': 'Battle Tips',
    'simulator.new': 'New Simulation',
    'simulator.share': 'Share Result',
    'simulator.confidence': 'Confidence',
    // Optimizer
    'optimizer.title': 'Build Optimizer',
    'optimizer.subtitle': 'Get your perfect build in seconds',
    'optimizer.goal': 'What\'s Your Goal?',
    'optimizer.pvp': 'PVP Dominance',
    'optimizer.pvp_desc': 'Win more duels',
    'optimizer.farm': 'Efficient Farming',
    'optimizer.farm_desc': 'Clear mobs faster',
    'optimizer.boss': 'Boss Killer',
    'optimizer.boss_desc': 'Defeat bosses easier',
    'optimizer.current': 'Current Build (Optional)',
    'optimizer.current_desc': 'Tell us what you have so we can build on it',
    'optimizer.current_fruit': 'Current Fruit',
    'optimizer.current_weapon': 'Current Weapon',
    'optimizer.keep_fruit': 'Keep my fruit',
    'optimizer.keep_weapon': 'Keep my weapon',
    'optimizer.optimize': 'Optimize My Build',
    'optimizer.recommended': 'Recommended Build',
    'optimizer.tier': 'Tier',
    'optimizer.upgrade_path': 'Upgrade Path',
    'optimizer.new': 'New Optimization',
    // Common
    'select.fruit': 'Select fruit...',
    'select.weapon': 'Select weapon...',
    'select.style': 'Select style...',
    'none_selected': 'None selected...',
    'balanced': 'Balanced',
    'melee': 'Melee',
    'fruit': 'Fruit',
    'defense': 'Defense',
    'favorable': 'FAVORABLE',
    'neutral': 'NEUTRAL',
    'unfavorable': 'UNFAVORABLE',
  },
};

export const useLanguage = create<LanguageStore>((set, get) => ({
  language: 'es',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => translations[get().language][key] || key,
}));
