import { create } from 'zustand';

type Language = 'es' | 'en';

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Index
    'hero.subtitle': 'Conoce tus probabilidades antes de pelear. Optimiza tu build en segundos.',
    'cta.simulate': 'Simular PVP',
    'cta.optimize': 'Optimizar Build',
    'cta.fruits': 'Guía de Frutas',
    'feature.simulator.title': 'Simulador de Matchups PVP',
    'feature.simulator.desc': 'Ingresa tu build y la de tu rival para obtener un análisis instantáneo con probabilidad de victoria, fortalezas y estrategias.',
    'feature.optimizer.title': 'Optimizador de Build',
    'feature.optimizer.desc': 'Dinos tu objetivo (PVP, Farmeo o Boss) y obtén una ruta de mejora personalizada con la mejor fruta, arma y stats.',
    'feature.fruits.title': 'Guía de Frutas',
    'feature.fruits.desc': 'Explora todas las frutas disponibles, sus características, counters y stats óptimas para cada una.',
    'stats.fruits': 'Frutas',
    'stats.weapons': 'Armas',
    'stats.free': 'Gratis',
    'footer.disclaimer': 'Herramienta fan-made. No afiliada con Blox Fruits o Roblox.',
    // Fruits page
    'fruits.title': 'Guía de Frutas',
    'fruits.subtitle': 'Explora todas las frutas disponibles en Blox Fruits',
    'fruits.search_placeholder': 'Buscar frutas...',
    'fruits.all_tiers': 'Todos los Tiers',
    'fruits.all_types': 'Todos los Tipos',
    'fruits.optimal_stats': 'Stats Óptimas',
    'fruits.strong_against': 'Fuerte contra',
    'fruits.weak_against': 'Débil contra',
    'fruits.no_results': 'No se encontraron frutas con estos filtros',
    'fruits.type_desc.paramecia': 'Frutas naturales con habilidades únicas y variadas',
    'fruits.type_desc.logia': 'Frutas elementales que otorgan inmunidad a ciertos tipos de daño',
    'fruits.type_desc.zoan': 'Frutas de bestia que permiten transformación',
    'fruits.tag.mobility': 'Movilidad',
    'fruits.tag.aoe': 'Área de Efecto',
    'fruits.tag.combo': 'Combo',
    'fruits.tag.burst': 'Burst',
    'fruits.tag.control': 'Control',
    'fruits.tag.tankiness': 'Tanque',
    'fruits.tag.utility': 'Utilidad',
    'fruits.tag.awakened': 'Despertada',
    'fruits.tag.transformation': 'Transformación',
    'fruits.tag.beginner_friendly': 'Amigable para Principiantes',
    // Simulator
    'simulator.title': 'Simulador PVP',
    'simulator.subtitle': 'Compara builds y conoce tus probabilidades',
    'simulator.your_build': 'Tu Build',
    'simulator.rival_build': 'Build Rival',
    'simulator.level': 'Nivel',
    'simulator.fruit': 'Fruta',
    'simulator.weapon': 'Arma',
    'simulator.gun': 'Pistola',
    'simulator.style': 'Estilo de Pelea',
    'simulator.stats': 'Enfoque de Stats',
    'simulator.simulate': 'Simular Matchup',
    'simulator.why_score': 'Por Qué Este Puntaje',
    'simulator.how_improve': 'Cómo Mejorar',
    'simulator.tips': 'Tips de Batalla',
    'simulator.new': 'Nueva Simulación',
    'simulator.share': 'Compartir Resultado',
    'simulator.confidence': 'Confianza',
    // Optimizer
    'optimizer.title': 'Optimizador de Build',
    'optimizer.subtitle': 'Obtén tu build perfecta en segundos',
    'optimizer.goal': '¿Cuál es Tu Objetivo?',
    'optimizer.pvp': 'Dominar PVP',
    'optimizer.pvp_desc': 'Ganar más duelos',
    'optimizer.farm': 'Farmeo Eficiente',
    'optimizer.farm_desc': 'Limpiar mobs más rápido',
    'optimizer.boss': 'Mata Bosses',
    'optimizer.boss_desc': 'Derrotar bosses fácilmente',
    'optimizer.current': 'Build Actual (Opcional)',
    'optimizer.current_desc': 'Dinos qué tienes para construir sobre eso',
    'optimizer.current_fruit': 'Fruta Actual',
    'optimizer.current_weapon': 'Arma Actual',
    'optimizer.keep_fruit': 'Mantener mi fruta',
    'optimizer.keep_weapon': 'Mantener mi arma',
    'optimizer.optimize': 'Optimizar Mi Build',
    'optimizer.recommended': 'Build Recomendada',
    'optimizer.tier': 'Tier',
    'optimizer.upgrade_path': 'Ruta de Mejora',
    'optimizer.new': 'Nueva Optimización',
    // Optimizer results
    'optimizer.obtain': 'Obtener {name}',
    'optimizer.get': 'Conseguir {name}',
    'optimizer.unlock': 'Desbloquear {name}',
    'optimizer.respec_stats': 'Reiniciar stats a distribución óptima',
    'optimizer.max_mastery': 'Maximizar mastery de {name} a 600',
    'optimizer.awaken': 'Despertar {name} (completar raid)',
    'optimizer.reason_core': '{name} es el núcleo de esta build de {objective}',
    'optimizer.reason_synergy': 'Sinergia perfecta con tu fruta para máximo {type}',
    'optimizer.reason_combo': 'Completa el potencial de combo de tu build',
    'optimizer.reason_stats': 'Distribución de stats optimizada para tu build',
    'optimizer.reason_mastery': 'Desbloquea todos los movimientos y maximiza el daño',
    'optimizer.reason_awakened': 'Los movimientos despertados son significativamente más fuertes',
    'optimizer.time_trading': '1-2 semanas (intercambio/caza)',
    'optimizer.time_days': '3-7 días',
    'optimizer.time_weeks': '1-2 semanas',
    'optimizer.time_instant': 'Instantáneo (requiere reset de stats)',
    'optimizer.time_grinding': '2-4 semanas de grind',
    'optimizer.build_prioritizes': 'Esta build prioriza: {priorities}',
    'optimizer.tier_meta': 'Build tier {tier} - Elección meta top',
    'optimizer.tier_reliable': 'Build tier {tier} - Fuerte y confiable',
    'optimizer.if_cant_get': 'Si no puedes conseguir {name}...',
    'optimizer.another_option': 'Otra opción sólida...',
    'optimizer.similar_performance': 'Rendimiento similar esperado',
    'optimizer.lower_tier_easier': 'Tier ligeramente más bajo pero más fácil de usar',
    'optimizer.lower_tier_effective': 'Tier ligeramente más bajo pero aún muy efectivo',
    'optimizer.less_mobile': 'Menos móvil pero potencialmente más daño',
    'optimizer.alternative_playstyle': 'Estilo de juego alternativo con efectividad similar',
    'optimizer.optimized_for': 'Build optimizada para {name} enfocada en {objective}',
    'optimizer.burst': 'burst',
    'optimizer.aoe': 'AoE',
    'optimizer.dps': 'DPS',
    'optimizer.win_rate': 'Tasa de Victoria',
    'optimizer.clear_speed': 'Velocidad de Limpieza',
    'optimizer.boss_kill_time': 'Tiempo de Muerte de Boss',
    'optimizer.improvement_pvp': '+30-50% en partidas clasificatorias',
    'optimizer.improvement_farm': '+40% más rápido limpiando mobs',
    'optimizer.improvement_boss': '-30% tiempo por boss',
    // Common
    'select.fruit': 'Seleccionar fruta...',
    'select.weapon': 'Seleccionar arma...',
    'select.gun': 'Seleccionar pistola...',
    'select.style': 'Seleccionar estilo...',
    'none_selected': 'Ninguno seleccionado...',
    'balanced': 'Balanceado',
    'melee': 'Melee',
    'fruit': 'Fruta',
    'defense': 'Defensa',
    'favorable': 'FAVORABLE',
    'neutral': 'NEUTRAL',
    'unfavorable': 'DESFAVORABLE',
    // Confidence levels
    'confidence.high': 'Alta',
    'confidence.medium': 'Media',
    'confidence.low': 'Baja',
    // Priority levels
    'priority.high': 'Alta',
    'priority.medium': 'Media',
    'priority.low': 'Baja',
    // Tip categories
    'tip.positioning': 'Posicionamiento',
    'tip.timing': 'Timing',
    'tip.combo': 'Combo',
    'tip.resource': 'Recursos',
    // Tip texts
    'tip.mobility': 'Usa tu movilidad para controlar la distancia de combate',
    'tip.zoning': 'Cierra la distancia rápidamente - no dejes que establezcan su zona',
    'tip.combo_full': 'Conecta tu combo completo antes de que puedan recuperarse',
    'tip.burst': 'Espera sus cooldowns antes de ir all-in',
    'tip.tankiness': 'No te comprometas demasiado - es una maratón, no un sprint',
    // Matchup reasons
    'reason.opponent': 'Oponente',
    'reason.tier_higher': 'es tier más alto que',
    'reason.tier_lower': 'es tier más bajo que',
    'reason.perfect_synergy': 'tiene sinergia perfecta con',
    'reason.poor_synergy': 'no tiene buena sinergia con',
    'reason.maximizes_combo': 'maximiza el potencial de combo de {name}',
    'reason.better_style': 'Considera un estilo de pelea que complemente mejor',
    'reason.optimal_stats': 'Tu distribución de stats es óptima para',
    'reason.your_fruit': 'tu fruta',
    'reason.stats_not_optimized': 'Tus stats no están optimizadas para tu build',
    'reason.level_advantage': 'Ventaja de nivel',
    'reason.level_disadvantage': 'Desventaja de nivel',
    'reason.levels': 'niveles',
    // Counters
    'counter.switch_fruit': 'Cambia a {name} para mejor matchup',
    'counter.try_weapon': 'Prueba {name} para mejor sinergia',
    'counter.switch_style': 'Cambia al estilo de pelea {name}',
    'counter.respec_stats': 'Reinicia stats para enfocarte en {stat}',
    'counter.no_improvements': '¡Tu build ya está bien optimizada para este matchup!',
    'counter.points': 'puntos',
    'counter.impact': 'Impacto',
    // Common words
    'common.and': 'y',
  },
  en: {
    // Index
    'hero.subtitle': 'Know your odds before you fight. Optimize your build in seconds.',
    'cta.simulate': 'Simulate PVP',
    'cta.optimize': 'Optimize Build',
    'cta.fruits': 'Fruits Guide',
    'feature.simulator.title': 'PVP Matchup Simulator',
    'feature.simulator.desc': 'Enter your build and your rival\'s to get instant matchup analysis with win probability, strengths, and counter strategies.',
    'feature.optimizer.title': 'Build Optimizer',
    'feature.optimizer.desc': 'Tell us your goal (PVP, Farming, or Boss) and get a personalized upgrade path with the best fruit, weapon, and stats.',
    'feature.fruits.title': 'Fruits Guide',
    'feature.fruits.desc': 'Explore all available fruits, their characteristics, counters, and optimal stats for each one.',
    'stats.fruits': 'Fruits',
    'stats.weapons': 'Weapons',
    'stats.free': 'Free',
    'footer.disclaimer': 'Fan-made tool. Not affiliated with Blox Fruits or Roblox.',
    // Fruits page
    'fruits.title': 'Fruits Guide',
    'fruits.subtitle': 'Explore all available fruits in Blox Fruits',
    'fruits.search_placeholder': 'Search fruits...',
    'fruits.all_tiers': 'All Tiers',
    'fruits.all_types': 'All Types',
    'fruits.optimal_stats': 'Optimal Stats',
    'fruits.strong_against': 'Strong against',
    'fruits.weak_against': 'Weak against',
    'fruits.no_results': 'No fruits found with these filters',
    'fruits.type_desc.paramecia': 'Natural fruits with unique and varied abilities',
    'fruits.type_desc.logia': 'Elemental fruits that grant immunity to certain damage types',
    'fruits.type_desc.zoan': 'Beast fruits that allow transformation',
    'fruits.tag.mobility': 'Mobility',
    'fruits.tag.aoe': 'Area of Effect',
    'fruits.tag.combo': 'Combo',
    'fruits.tag.burst': 'Burst',
    'fruits.tag.control': 'Control',
    'fruits.tag.tankiness': 'Tankiness',
    'fruits.tag.utility': 'Utility',
    'fruits.tag.awakened': 'Awakened',
    'fruits.tag.transformation': 'Transformation',
    'fruits.tag.beginner_friendly': 'Beginner Friendly',
    // Simulator
    'simulator.title': 'PVP Simulator',
    'simulator.subtitle': 'Compare builds and know your odds',
    'simulator.your_build': 'Your Build',
    'simulator.rival_build': 'Rival Build',
    'simulator.level': 'Level',
    'simulator.fruit': 'Fruit',
    'simulator.weapon': 'Weapon',
    'simulator.gun': 'Gun',
    'simulator.style': 'Fighting Style',
    'simulator.stats': 'Stat Focus',
    'simulator.simulate': 'Simulate Matchup',
    'simulator.why_score': 'Why This Score',
    'simulator.how_improve': 'How to Improve',
    'simulator.tips': 'Battle Tips',
    'simulator.new': 'New Simulation',
    'simulator.share': 'Share Result',
    'simulator.confidence': 'Confidence',
    // Optimizer
    'optimizer.title': 'Build Optimizer',
    'optimizer.subtitle': 'Get your perfect build in seconds',
    'optimizer.goal': 'What\'s Your Goal?',
    'optimizer.pvp': 'PVP Dominance',
    'optimizer.pvp_desc': 'Win more duels',
    'optimizer.farm': 'Efficient Farming',
    'optimizer.farm_desc': 'Clear mobs faster',
    'optimizer.boss': 'Boss Killer',
    'optimizer.boss_desc': 'Defeat bosses easier',
    'optimizer.current': 'Current Build (Optional)',
    'optimizer.current_desc': 'Tell us what you have so we can build on it',
    'optimizer.current_fruit': 'Current Fruit',
    'optimizer.current_weapon': 'Current Weapon',
    'optimizer.keep_fruit': 'Keep my fruit',
    'optimizer.keep_weapon': 'Keep my weapon',
    'optimizer.optimize': 'Optimize My Build',
    'optimizer.recommended': 'Recommended Build',
    'optimizer.tier': 'Tier',
    'optimizer.upgrade_path': 'Upgrade Path',
    'optimizer.new': 'New Optimization',
    // Optimizer results
    'optimizer.obtain': 'Obtain {name}',
    'optimizer.get': 'Get {name}',
    'optimizer.unlock': 'Unlock {name}',
    'optimizer.respec_stats': 'Respec stats to optimal distribution',
    'optimizer.max_mastery': 'Max {name} mastery to 600',
    'optimizer.awaken': 'Awaken {name} (complete raid)',
    'optimizer.reason_core': '{name} is the core of this {objective} build',
    'optimizer.reason_synergy': 'Perfect synergy with your fruit for maximum {type}',
    'optimizer.reason_combo': 'Completes your build\'s combo potential',
    'optimizer.reason_stats': 'Optimized stat distribution for your build',
    'optimizer.reason_mastery': 'Unlock all moves and maximize damage',
    'optimizer.reason_awakened': 'Awakened moves are significantly stronger',
    'optimizer.time_trading': '1-2 weeks (trading/hunting)',
    'optimizer.time_days': '3-7 days',
    'optimizer.time_weeks': '1-2 weeks',
    'optimizer.time_instant': 'Instant (requires stat reset)',
    'optimizer.time_grinding': '2-4 weeks of grinding',
    'optimizer.build_prioritizes': 'This build prioritizes: {priorities}',
    'optimizer.tier_meta': 'Tier {tier} build - Top meta choice',
    'optimizer.tier_reliable': 'Tier {tier} build - Strong and reliable',
    'optimizer.if_cant_get': 'If you can\'t get {name}...',
    'optimizer.another_option': 'Another solid option...',
    'optimizer.similar_performance': 'Similar performance expected',
    'optimizer.lower_tier_easier': 'Slightly lower tier but easier to use',
    'optimizer.lower_tier_effective': 'Slightly lower tier but still very effective',
    'optimizer.less_mobile': 'Less mobile but potentially more damage',
    'optimizer.alternative_playstyle': 'Alternative playstyle with similar effectiveness',
    'optimizer.optimized_for': 'Optimized build for {name} focusing on {objective}',
    'optimizer.burst': 'burst',
    'optimizer.aoe': 'AoE',
    'optimizer.dps': 'DPS',
    'optimizer.win_rate': 'Win Rate',
    'optimizer.clear_speed': 'Clear Speed',
    'optimizer.boss_kill_time': 'Boss Kill Time',
    'optimizer.improvement_pvp': '+30-50% in ranked matches',
    'optimizer.improvement_farm': '+40% faster mob clearing',
    'optimizer.improvement_boss': '-30% time per boss',
    // Common
    'select.fruit': 'Select fruit...',
    'select.weapon': 'Select weapon...',
    'select.gun': 'Select gun...',
    'select.style': 'Select style...',
    'none_selected': 'None selected...',
    'balanced': 'Balanced',
    'melee': 'Melee',
    'fruit': 'Fruit',
    'defense': 'Defense',
    'favorable': 'FAVORABLE',
    'neutral': 'NEUTRAL',
    'unfavorable': 'UNFAVORABLE',
    // Confidence levels
    'confidence.high': 'High',
    'confidence.medium': 'Medium',
    'confidence.low': 'Low',
    // Priority levels
    'priority.high': 'High',
    'priority.medium': 'Medium',
    'priority.low': 'Low',
    // Tip categories
    'tip.positioning': 'Positioning',
    'tip.timing': 'Timing',
    'tip.combo': 'Combo',
    'tip.resource': 'Resource',
    // Tip texts
    'tip.mobility': 'Use your mobility to control engagement distance',
    'tip.zoning': 'Close the gap quickly - don\'t let them set up their zoning',
    'tip.combo_full': 'Land your full combo before they can recover',
    'tip.burst': 'Wait for their cooldowns before going all-in',
    'tip.tankiness': 'Don\'t overcommit - it\'s a marathon, not a sprint',
    // Matchup reasons
    'reason.opponent': 'Opponent',
    'reason.tier_higher': 'is higher tier than',
    'reason.tier_lower': 'is lower tier than',
    'reason.perfect_synergy': 'has perfect synergy with',
    'reason.poor_synergy': 'doesn\'t synergize well with',
    'reason.maximizes_combo': 'maximizes {name}\'s combo potential',
    'reason.better_style': 'Consider a fighting style that better complements',
    'reason.optimal_stats': 'Your stat distribution is optimal for',
    'reason.your_fruit': 'your fruit',
    'reason.stats_not_optimized': 'Your stats aren\'t optimized for your build',
    'reason.level_advantage': 'Level advantage',
    'reason.level_disadvantage': 'Level disadvantage',
    'reason.levels': 'levels',
    // Counters
    'counter.switch_fruit': 'Switch to {name} for better matchup',
    'counter.try_weapon': 'Try {name} for better synergy',
    'counter.switch_style': 'Switch to {name} fighting style',
    'counter.respec_stats': 'Respec stats to focus on {stat}',
    'counter.no_improvements': 'Your build is already well optimized for this matchup!',
    'counter.points': 'points',
    'counter.impact': 'Impact',
    // Common words
    'common.and': 'and',
  },
};

export const useLanguage = create<LanguageStore>((set, get) => ({
  language: 'es',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => translations[get().language][key] || key,
}));
